name: Scheduler (Daily)

# NOTE: GitHub Action's scheduler is always set to UTC+0. So 9am should be set at 0am for JST (UTC+9)
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule

# '0 23 * * *' ==  8am in JST (UTC+9)
# '0 0 * * *'  ==  9am in JST (UTC+9)
# '0 1 * * *'  == 10am in JST (UTC+9)
# '59 23 * * *' task will be completed after 9am in JST
on:
  schedule:
    - cron:  '59 23 * * *'

    # [DEBUG ONLY] Every 5 minutes
    # https://github.blog/changelog/2019-11-01-github-actions-scheduled-jobs-maximum-frequency-is-changing
    #- cron:  '*/5 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Download codes from GitHub
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: 💎 Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: 🧪 Install Ruby gems
      run: |
        bundle install --jobs 4 --retry 3

    - name: 📍 Fetch data, generate geojson, and compact it for target area：高田馬場
      run: |
        bundle exec ruby upsert_markers.rb  takadanobaba
        bundle exec ruby upsert_geojson.rb  takadanobaba
        bundle exec ruby compact_geojson.rb takadanobaba

    - name: 🆙 Commit latest data to update BabaMap (if any)
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          git config --global user.name  "Yohei Yasukawa"
          git config --global user.email "yohei@yasslab.jp"
          git checkout main
          git add Gemfile.lock
          git add takadanobaba.yml
          git add takadanobaba.geojson
          git commit -m '🤖 Upsert map data for BabaMap'
          git push origin main
        fi
      env:
        GITHUB_TOKEN:

    - name: 🔧 Build & Test
      run: |
        JEKYLL_ENV=production bundle exec jekyll build
        JEKYLL_ENV=production bundle exec jekyll doctor
