name: Build & Test
on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Download codes from GitHub
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: 💎 Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: 🧪 Install gems
      run: |
        bundle install --jobs 4 --retry 3

    - name: 🔧 Build
      run: |
        JEKYLL_ENV=production bundle exec jekyll build
        JEKYLL_ENV=production bundle exec jekyll doctor

    - name: 🔍 Test
      run: |
        SKIP_BUILD=true bundle exec rake test
